# Generated by Django 5.1.1 on 2025-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='availability',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
