# Generated by Django 5.1.1 on 2025-11-06 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacherprofile_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('virtual_room_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Sesion en linea',
                'verbose_name_plural': 'Sesiones en linea',
                'ordering': ('-start_time',),
                'constraints': [models.UniqueConstraint(fields=('teacher', 'student', 'start_time', 'end_time'), name='unique_session_teacher_student_time')],
            },
        ),
    ]
